# Generated by Django 4.2.11 on 2024-05-27 23:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado', models.DateTimeField(default=datetime.datetime.now)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Producto', models.CharField(max_length=200)),
                ('Precio_Producto', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('Cantidad_Producto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Categoria', models.CharField(max_length=100)),
                ('Descripcion_Categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo_Producto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Producto', models.CharField(max_length=70)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('Precio', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('Stock', models.PositiveIntegerField(default=0)),
                ('Id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimatiApp.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=1)),
                ('Precio', models.FloatField(blank=True)),
                ('Carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimatiApp.carrito')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimatiApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo_Electronico', models.CharField(max_length=130)),
                ('Direccion', models.CharField(max_length=120)),
                ('Telefono', models.IntegerField(default=2000)),
                ('Id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
