# Generated by Django 4.2.11 on 2024-05-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('Nro_Pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('DNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimatiApp.cliente')),
                ('Id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimatiApp.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
    ]
