# Generated by Django 4.2.11 on 2024-05-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0002_alter_carrito_usuario_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
