# Generated by Django 4.2.11 on 2024-05-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0002_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Usuario', models.CharField(max_length=100)),
                ('Correo_Usuario', models.CharField(max_length=100)),
                ('Numero_Telefono', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
